### ISSUE TITLE
Design: Update Figma components tokens

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#729] opened 2024-02-19 18:48 UTC
Some Figma components currently use base tokens for text, border + background colours, they should be using component-specific tokens instead.

- [ ] Update Figma components to use the correct component tokens for text, border + background for each component.
- [ ] Use new global background tokens for non-component specific styling within Figma.

**Comment by realdylanzheng** [comment] 2024-06-19 00:34
@adorayi this issue is essentially a duplicate of #743

**Closed** 2024-09-04 15:21 UTC
Labels: Groomed
