### ISSUE TITLE
Select component Figma updates

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#1002] opened 2024-06-27 19:14 UTC
- [x] Input is outside of frame
- [x] FR select component with error and focus state has too much spacing

<img width="1664" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlhQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac935b7359d8dfe4c14645b2be71f570c82ce415/image.png" alt="image.png" />

## Done when
- [x] Spacing is reviewed
- [x] [Figma comment](https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB?node-id=114-3340#852192182) is marked as resolved

## Development impact
**None**

**Comment by realdylanzheng** [comment] 2024-07-12 17:49
@RavinaSamaroo | cc: @adorayi 
- **Error** is a false-by-default boolean within the Select component and when it gets toggled to true it pushes the select field out of the visual frame, however upon inspecting the component's layers the select field is where it's supposed to be in the layer hierarchy (child of Select field, which is child of Select). It's just Figma behaviour, not a bug on our end.
- The spacing has been fixed on the [FR Select](https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB/Syst%C3%A8me-de-design-GC?node-id=912-11255&t=YuAym9OtyhNjSoIs-4)

Issue may be closed upon review, thanks.

**Comment by RavinaSamaroo** [comment] 2024-07-19 02:51
@realdylanzheng this was actually an issue with the component being set to fixed height instead of hug contents. I am fixing it as part of the date input error state fixes.

**Closed** 2024-07-29 18:16 UTC
Labels: design
